version: '3'

services:
  api:
    build:
      context: ./booksApi
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongo

  ssr:
    build:
      context: ./ssr
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:3000'
    depends_on:
      - mongo
      - api

  mongo:
    image: mongo
